# 예외처리
프로그램을 만들다 보면 수많은 오류를 만난다.

오류가 발생하는 이유는 프로그램이 잘못 동작하는 것을 막기 위함이지만 

상황에 따라 오류를 무시해야 할 때도 있을 것이다.

이때 ```try``` , ```except```를 사용해서 예외적으로 오류를 처리할 수 있다.

## 오류 예외 처리 기법
### try-except문
다음과 같은 리스트가 있다.
```python
people = [
    {'name': '짱구', 'age': 20},
    {'name': '철수', 'age': 38},
    {'name': '유리', 'age': 7},
    {'name': '훈이', 'age': 17},
    {'name': '맹구', 'age': 27},
]
```

만약 20살이 넘는 사람만 출력해야 할 경우 다음과 같다.
```python
people = [
    {'name': '짱구'},
    {'name': '철수', 'age': 38},
    {'name': '유리', 'age': 7},
    {'name': '훈이', 'age': 17},
    {'name': '맹구', 'age': 27},
]

for i in people:
    if i['age'] > 20:
        print(i['name'])

# 결과
철수
맹구
```
위 코드가 실행될때 만약 리스트 안에 딕셔너리중 하나의 'age'를 없애보겠다.
```python
people = [
    {'name': '짱구'},
    {'name': '철수', 'age': 38},
    {'name': '유리', 'age': 7},
    {'name': '훈이', 'age': 17},
    {'name': '맹구','age': 25},
]

for i in people:
    if i['age'] > 20:
        print(i['name'])
        
# 결과
KeyError: 'age'
```
Error 가 발생한 시점에서 코드는 종료된다.

이때 try-except문을 사용하여 오류가 발생해도 코드가 종료되지 않게 한다.
```python
people = [
    {'name': '짱구'},
    {'name': '철수', 'age': 38},
    {'name': '유리', 'age': 7},
    {'name': '훈이', 'age': 17},
    {'name': '맹구','age': 25},
]

for i in people:
    try: # try 안에 코드를 실행한다.
        if i['age'] > 20:
            print(i['name'])
    except: print(i['name'] , " - Error")
    # 에러가 발생하면 'name' 값 , Error 문장 출력하고 넘어간다.

# 결과
짱구 - Error
철수
맹구
```