# 예외처리
## 프로그램 오류
프로그램이 실행 중 어떤 원인에 의해서 오작동을 하거나 비정상적으로 종료되는 경우가 있다.

이러한 결과를 초래하는 원인을 ```프로그램 에러``` or ```오류```라고 한다.

프로그램 에러는 발생시점에 따라 3가지 종류로 나눌 수 있다.
- ```컴파일 에러(compil-time error)``` : 컴파일 할 때 발생하는 에러
- ```런타임 에러(runtime error)``` : 실행 할 때 발생하는 에러
- ```논리적 에러(logical error)``` : 작성 의도와 다르게 동작

#### 컴파일(Compile)
컴퓨터는 0과 1로만 모든 명령을 이해하고 실행한다.

우리가 'B' 라는 문자를 입력해도 컴퓨터는 이것을 0과 1로 이루어진 이진코드로 해석한다.

우리가 입력한 문자를 컴퓨터가 이해할 수 있는 언어로 바꿔주는 기능을 컴파일이라 한다.


## 예외처리(Exception, Error Handling)
코드를 완벽하게 작성했다 해서 항상 성공적으로 프로그램이 실행되는 것은 아니다.

다양한 예외 상황에 대응하기 위해 ```예외 처리 코드```가 필요하다.
### 예외처리의 목적
1. 예외의 발생으로 인한 실행 중인 프로그램의 비정상 종료를 막기 위함
2. 개발자에게 알려서 기존 코드를 보완할 수 있도록 한다.

자바는 ```상속을 이용해서 모든 예외를 표현```한다.

모든 예외 처리를 담당하는 클래스의 최상위에는 ```Throwable```이 있으며 

**모든 예외 클래스는 Throwable의 자손 클래스**다.

### Throwable 에 대표적인 두 종류의 자식 클래스
#### 1. 에러(Error)

프로그램 코드에 의해 수습될수 없는 , 프로그램이 종료되어야 하는 심각한 오류를 뜻한다.

대부분 컴퓨터나 ```JVM```이 시스템적으로 동작할 수 없는 상황을 표현한다.

#### OOME(OutOfMemoryError)
```
Java는 JVM내의 Heap이라는 메모리 공간을 운영체제로부터 할당 받아 사용한다.

할당 받을 수 있는 최대 메모리 이상을 사용하면, JVM이 다운될 수 밖에 없는데,

이때 OutOfMemoryError가 나면서 프로그램이 종료된다.

자바의 대표적인 에러 상황으로 줄여서 OOME 라고도 한다.
```

#### 2. 예외(Exception)
프로그램 코드에 의해서 수습될 수 있는 다소 미약한 오류를 뜻하며

프로그램이 종료되지는 않지만 예외나 문제상황을 표한하기 위해 사용한다.

자바에는 미리 정의 되어있는 예외 클래스 들이 있다. 기본적으로 이미 있는 것을 사용하되,

필요한 것으로 표현할 수 없거나 구체적인 목적을 가진 예외를 정의하고 싶다면,

```Throwable``` 또는 그 하위에 있는 예외 클래스를 상속받아서

나만의 예외 클래스를 정의할 수 있다.

- 자바의 기본 예외 클래스들 중 대표적인 것들의 상속 관계도

![01](https://user-images.githubusercontent.com/108924832/202237805-f001bdd8-6516-45fd-8510-3f5e9cd48705.PNG)


https://media.vlpt.us/images/codepark_kr/post/a70025be-d97d-4ba4-81de-bf9b8fe48d2b/ExceptionClassHierarchy.png

프로그래밍을 하다 발생하는 대부분의 예외 상황은 ```Exception ``` 종류일 확률이 높다.

- 프로그램 실행 도중 발생하는 Exception은 ```RuntimeException```을 상속받아 정의한다.

- 파일을 읽고 쓰거나, 원격에 있는 저장소로부터 데이터를 읽고 쓸 때 나는 에러를 표현하려면 

    ```IOException```을 상속받아서 정의한다.

### try-catch(-finally) 형식
```java
try {
    // 예외가 발생할 가능성이 있는 코드를 구현한다.
} catch (FileNotFoundException e) {
    // FileNotFoundException이 발생했을 경우,이를 처리하기 위한 코드를 구현한다.
} catch (IOException e) {
    // FileNotFoundException이 아닌 IOException이 발생했을 경우
    // 이를 처리하기 위한 코드를 구현한다.
} finally {
    // 예외의 발생여부에 관계없이 항상 수행되어야하는 코드를 구현합니다.
}
```
```finally```구문은 필수는 아니다.

만약 예외가 발생하지 않으면 ```try → finally 순으로 실행```된다.

예외는 중복 ```catch 블럭```을 사용하여 다양한 예외처리를 수행할 수 있다.

중복 catch 블럭을 사용할 때는 먼저 선언된 catch 블럭부터 확인한다.

앞의 catch 블럭에서 잡혔다면, 뒤의 catch 블럭으로는 전파되지 않는다.

그리고 좁은 범위의 예외부터 앞에 선언하는 것이 좋다.
- 좁은 범위 : 상속관계에서 자식 클래스에 위치 할수록 좁은 범위
```
IOException이 발생할 것 같아 예외처리를 하고, 
그 외의 예외도 예외처리를 하고 싶다면 IOException을 catch 하는 구문을 먼저 작성하고, 
Exception 을 catch하는 구문을 그 뒤에 작성합니다.
```

### try-catch-finally 연습
- number 를 10으로 나누며, 반복문을 사용해 i는 1씩 감소한다.
- i가 0이 되면 10으로 나눌 수 없기 떼문에 예외가 발생할 것이다.
- 예외처리한다.
```java
// Main
public class Main {
  public static void main(String[] args) {
    int number = 10;
    int result;

    for (int i = 10; i >= 0; i--) {
      try {
        // 예외가 발생할 가능성(i = 0) 이 있는 코드
        result = number / i;
        System.out.println("결과 : " + result);
        // catch로 예외를 처리한다.
      } catch (Exception e) {
        System.out.println("예외(Exception e) 발생 : " + e.getMessage());
      } finally {
        System.out.println("finally 는 예외 구분없이 실행됩니다.");
      }
    }
  }
}

// 결과
결과 : 1
finally 는 예외 구분없이 실행됩니다.
결과 : 1 
 finally 는 예외 구분없이 실행됩니다.
결과 : 1
finally 는 예외 구분없이 실행됩니다.
결과 : 1
finally 는 예외 구분없이 실행됩니다.
결과 : 1
finally 는 예외 구분없이 실행됩니다.
결과 : 2
finally 는 예외 구분없이 실행됩니다.
결과 : 2
finally 는 예외 구분없이 실행됩니다.
결과 : 3
finally 는 예외 구분없이 실행됩니다.
결과 : 5
finally 는 예외 구분없이 실행됩니다.
결과 : 10
finally 는 예외 구분없이 실행됩니다.
예외(Exception e) 발생 : / by zero // number를 0으로 나누려 했기 때문에 발생한 예외
finally 는 예외 구분없이 실행됩니다.
```

### 메소드에서의 예외 선언
```catch문```을 이용해서 에외처리를 하지 않은 경우, 메소드에 ```throws```로 예외가

발생할 수 있다는 것을 알려주어야 한다. ```throws ``` 키워드가 있는 함수를 호출한다면,

```caller```쪽에서 ```catch```와 관련된 코드를 작성해주어야 한다.
```java
void method() throws IndexOutOfBoundsException, IllegalArgumentException {
    //메소드의 내용
}
```

## 예외, 에러 처리 퀴즈
### 퀴즈 내용
```divide() 함수```는 매개변수(parameter)에 들어오는 값에 따라서 

```ArithmeticException```과 ```ArrayIndexOutOfBoundsException```이 발생할 수 있다.

1. throws 키워드를 통해서 divide() 함수에서 발생할 수 있는 
   ```exception```의 종류가 무엇인지 알려야 한다.
2. Main 함수에서 try-catch 문을 이용해서, 다음 동작을 구현해라.
- ```ArithmeticException```이 발생할 때는 잘못된 계산임을 알리는 문구를 출력할 것
- ```ArrayIndexOutOfBoundsException```이 발생할 때는 
  현재 배열의 index범위를 알려주는 문구를 출력할 것

### 퀴즈풀이
```java
// class


// Main

// 결과
```









